// OBJECT

//STRING
var str =new String(" Hello!")
console.log(typeof str)
console.log(str)
console.log(str.length)
console.log(str.charAt(2))
console.log(str.charCodeAt(2))
console.log(str.toUpperCase())
console.log(str.toLowerCase())
console.log(str.substring(1,4))
console.log(str.concat(" World"))
console.log(str.trim())
console.log(str.includes("lo"))

//MATH
console.log(Math.PI)
console.log(Math.E)
console.log(Math.SQRT2)
console.log(Math.SQRT1_2)
console.log(Math.LN2)
console.log(Math.LN10)
console.log(Math.LOG2E)
console.log(Math.LOG10E)
console.log(Math.sqrt(9))
console.log(Math.abs(-2998))
console.log(Math.round(34.9904))
console.log(Math.ceil(78.4))
console.log(Math.floor(78.94))
console.log(Math.random())
console.log(Math.max(9,4,5,9,55 ))
console.log(Math.min(9,4,5,9,55 ))
console.log(Math.pow(2,8))

//DATE
console.log(Date())
console.log(new Date())
console.log(new Date('2024-12-23'))
console.log(Date.now())
console.log(Date.parse("2024-12-23"))
console.log(new Date(13333333))
var now=new Date()

console.log(now.getDate())
console.log(now.setDate(9))
console.log(now.getMonth())
console.log(now.setMonth(6))
console.log(now.getFullYear())
console.log(now.setFullYear(2004))
console.log(now.getDay())
console.log(now.getHours())
console.log(now.setHours(17))
console.log(now.getMinutes())
console.log(now.setMinutes(57))
console.log(now.getSeconds())
console.log(now.setSeconds(43))
console.log(now.getMilliseconds())
console.log(now.setMilliseconds(43))
console.log(now.getTime())
console.log(now.setTime(43))

// console.log(now.setSeconds())
