// Array

let arr=["apple",2,4,"ee",'$','_']
console.log(arr) 
console.log(arr[4])
arr.sort()
console.log(arr)
console.log(arr[4])
console.log(arr.length)
console.log(arr.push(49))
console.log(arr)
console.log(arr.pop())
console.log(arr)
console.log(arr.shift())
console.log(arr.unshift(3))
console.log(arr)
console.log(arr.indexOf("$"))
console.log(arr)
console.log(arr.includes(3))
console.log(arr)
console.log("splice: ",arr.splice(1,3,3,4,4))
console.log(arr)
console.log(arr.slice(0,4))
console.log(arr)
console.log(arr.concat([23,56,89]))
console.log(arr)
console.log(arr.join(" ~~~ "))
console.log(arr)
console.log(arr.reverse())
console.log(arr)
console.log(arr.sort((a,b)=>a-b))
console.log(arr)
console.log(arr.map(x=>x*x))
console.log(arr)
console.log(arr.forEach(num=>console.log(num*3)))
console.log(arr)
console.log(arr.filter(X=>X%2===0))
console.log(arr)
console.log(arr.reduce((a,b)=>a+b,0))
console.log(arr)
console.log(arr.find(x=> x>2))
console.log(arr)
console.log(Array.isArray(arr))
console.log(arr.every(x=>x>3))
console.log(arr.at(2))
console.log(arr.at(-2))
console.log(arr)
console.log(arr.toString())
console.log(arr)
console.log(arr)
console.log(arr)

